# Generated by Django 4.1.11 on 2023-10-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('AttendanceId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('EmployeeTime', models.CharField(max_length=500)),
                ('EmployeeDate', models.DateField()),
            ],
        ),
    ]
